[package]
name = "colbert_rs"
edition = "2021"
version = "0.1.0"

[[bin]]
name = "colbert_rs"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
